list = []
list.append(1)
list.append(2)
list.append(4)
list.append(-2)
list.insert(1,6)
print(list)
list.remove(2)
print(list)
list.append(5)
print(list)
list.sort()
print(list)
list.pop()
print(list)
list.reverse()
print(list)